name: diary_ai_backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dart_jsonwebtoken: ^2.7.1
  dart_openai: ^1.4.6
  envied: ^0.3.0
  mongo_dart: ^0.8.2
  shelf_cors_headers: ^0.1.4

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
